In [13]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import torch


iris = load_iris()


df = pd.DataFrame(iris.data, columns=iris.feature_names)

df["target"] = iris.target

df.sample(10)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
48,5.3,3.7,1.5,0.2,0
139,6.9,3.1,5.4,2.1,2
107,7.3,2.9,6.3,1.8,2
83,6.0,2.7,5.1,1.6,1
109,7.2,3.6,6.1,2.5,2
27,5.2,3.5,1.5,0.2,0
6,4.6,3.4,1.4,0.3,0
19,5.1,3.8,1.5,0.3,0
62,6.0,2.2,4.0,1.0,1
61,5.9,3.0,4.2,1.5,1

In [14]:
df.shape

(150, 5)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [16]:
df.describe().T

                   count      mean       std  min  25%   50%  75%  max
sepal length (cm)  150.0  5.843333  0.828066  4.3  5.1  5.80  6.4  7.9
sepal width (cm)   150.0  3.057333  0.435866  2.0  2.8  3.00  3.3  4.4
petal length (cm)  150.0  3.758000  1.765298  1.0  1.6  4.35  5.1  6.9
petal width (cm)   150.0  1.199333  0.762238  0.1  0.3  1.30  1.8  2.5
target             150.0  1.000000  0.819232  0.0  0.0  1.00  2.0  2.0

In [17]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(1)

In [19]:
df[df.duplicated()]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
142,5.8,2.7,5.1,1.9,2

In [20]:
df = df.drop_duplicates()

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
X = df.drop("target", axis=1)
y = df["target"]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [25]:
X_train.dtype

dtype('float64')

In [26]:
X_test.dtype

dtype('float64')

In [27]:
y_train.dtype

dtype('int64')

In [28]:
y_test.dtype

dtype('int64')

In [29]:
# convert to tens
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train.values)
y_test_tensor = torch.from_numpy(y_test.values)

In [30]:
X_train_tensor.dtype

torch.float32

In [31]:
X_test_tensor.dtype

torch.float32

In [32]:
y_train_tensor.dtype

torch.int64

In [33]:
y_test_tensor.dtype

torch.int64