In [128]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import torch


iris = load_iris()


df = pd.DataFrame(iris.data, columns=iris.feature_names)

df["target"] = iris.target

df.sample(10)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
47,4.6,3.2,1.4,0.2,0
54,6.5,2.8,4.6,1.5,1
19,5.1,3.8,1.5,0.3,0
116,6.5,3.0,5.5,1.8,2
26,5.0,3.4,1.6,0.4,0
92,5.8,2.6,4.0,1.2,1
18,5.7,3.8,1.7,0.3,0
75,6.6,3.0,4.4,1.4,1
51,6.4,3.2,4.5,1.5,1
33,5.5,4.2,1.4,0.2,0

In [129]:
df.shape

(150, 5)

In [130]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [131]:
df.describe().T

                   count      mean       std  min  25%   50%  75%  max
sepal length (cm)  150.0  5.843333  0.828066  4.3  5.1  5.80  6.4  7.9
sepal width (cm)   150.0  3.057333  0.435866  2.0  2.8  3.00  3.3  4.4
petal length (cm)  150.0  3.758000  1.765298  1.0  1.6  4.35  5.1  6.9
petal width (cm)   150.0  1.199333  0.762238  0.1  0.3  1.30  1.8  2.5
target             150.0  1.000000  0.819232  0.0  0.0  1.00  2.0  2.0

In [132]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [133]:
df.duplicated().sum()

np.int64(1)

In [134]:
df[df.duplicated()]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
142,5.8,2.7,5.1,1.9,2

In [135]:
df = df.drop_duplicates()

In [136]:
df.duplicated().sum()

np.int64(0)

In [137]:
X = df.drop("target", axis=1)
y = df["target"]

In [138]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [139]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [140]:
X_train.dtype

dtype('float64')

In [141]:
X_test.dtype

dtype('float64')

In [142]:
y_train.dtype

dtype('int64')

In [143]:
y_test.dtype

dtype('int64')

In [144]:
# convert to tensor
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train.values)
y_test_tensor = torch.from_numpy(y_test.values)

In [145]:
X_train_tensor.dtype

torch.float32

In [146]:
X_test_tensor.dtype

torch.float32

In [147]:
y_train_tensor.dtype

torch.int64

In [148]:
y_test_tensor.dtype

torch.int64

In [149]:
X_train_tensor.shape[1]

4

In [150]:
y_train_tensor.shape

torch.Size([119])

In [151]:
import torch.nn as nn
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network=nn.Sequential(
            nn.Linear(num_features,3)
            )
    def forward(self,features):
        return self.network(features)

In [153]:
model = Model(X_train_tensor.shape[1])  
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)
loss_function = nn.CrossEntropyLoss()   

epochs = 35
for epoch in range(epochs):
    optimizer.zero_grad()
    y_pred = model(X_train_tensor)
    loss = loss_function(y_pred, y_train_tensor)
    loss.backward()
    optimizer.step()
    print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 1, Loss: 1.1653555631637573
Epoch 2, Loss: 0.8645715117454529
Epoch 3, Loss: 0.6706343293190002
Epoch 4, Loss: 0.5509945154190063
Epoch 5, Loss: 0.47627344727516174
Epoch 6, Loss: 0.4279416799545288
Epoch 7, Loss: 0.39539942145347595
Epoch 8, Loss: 0.37225398421287537
Epoch 9, Loss: 0.3543633818626404
Epoch 10, Loss: 0.3391974866390228
Epoch 11, Loss: 0.32548168301582336
Epoch 12, Loss: 0.31273049116134644
Epoch 13, Loss: 0.3008190393447876
Epoch 14, Loss: 0.2897041440010071
Epoch 15, Loss: 0.27930188179016113
Epoch 16, Loss: 0.2694774568080902
Epoch 17, Loss: 0.26008832454681396
Epoch 18, Loss: 0.2510302662849426
Epoch 19, Loss: 0.24226249754428864
Epoch 20, Loss: 0.23380622267723083
Epoch 21, Loss: 0.2257242649793625
Epoch 22, Loss: 0.21809205412864685
Epoch 23, Loss: 0.21097004413604736
Epoch 24, Loss: 0.2043835073709488
Epoch 25, Loss: 0.19831636548042297
Epoch 26, Loss: 0.19271771609783173
Epoch 27, Loss: 0.1875181794166565
Epoch 28, Loss: 0.1826484650373459
Epoch 29, Loss: 0.17805349826812744
Epoch 30, Loss: 0.17369772493839264
Epoch 31, Loss: 0.16956216096878052
Epoch 32, Loss: 0.1656370908021927
Epoch 33, Loss: 0.16191457211971283
Epoch 34, Loss: 0.15838447213172913
Epoch 35, Loss: 0.15503396093845367