In [96]:
import numpy as np
import torch
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [97]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [98]:
df.shape

(569, 33)

In [99]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [100]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [101]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [102]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [103]:
X_train

array([[ 0.13324928,  0.7791705 ,  0.18501235, ..., -0.06399584,
        -1.0563852 , -0.22015905],
       [-0.63763608, -0.43689714, -0.65147413, ..., -0.38583903,
        -1.11729561, -1.29366787],
       [-1.10302243, -0.61519277, -1.0802822 , ..., -0.47960798,
        -0.36232711,  0.58320244],
       ...,
       [ 0.82419096,  0.22599687,  0.73645539, ..., -0.07776289,
         0.57376972, -1.05619966],
       [ 1.19535799, -0.15802449,  1.1051889 , ...,  0.64883177,
         0.46316924, -0.80075793],
       [-0.44634231, -0.04601826, -0.41449034, ..., -0.33704246,
        -1.27598326, -0.66459497]], shape=(455, 30))

In [104]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [105]:
y_train

array([0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0])

In [106]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()   
y_train_tensor = torch.from_numpy(y_train).float().view(-1, 1)
y_test_tensor = torch.from_numpy(y_test).float().view(-1, 1)

In [107]:
X_train_tensor.shape

torch.Size([455, 30])

In [108]:

import torch.nn as nn

class MySimpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()

        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate Binary Cross Entropy loss manually
        loss = -(y * torch.log(y_pred) +(1 - y) * torch.log(1 - y_pred)).mean()
        return loss

In [109]:
learning_rate = 0.1
epochs = 25

In [110]:
X_train_tensor.shape[1]

30

In [117]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.831395149230957
Epoch: 2, Loss: 0.5920587182044983
Epoch: 3, Loss: 0.4729991853237152
Epoch: 4, Loss: 0.4044063985347748
Epoch: 5, Loss: 0.3591177761554718
Epoch: 6, Loss: 0.3265298306941986
Epoch: 7, Loss: 0.30169570446014404
Epoch: 8, Loss: 0.2819812595844269
Epoch: 9, Loss: 0.2658465802669525
Epoch: 10, Loss: 0.252327024936676
Epoch: 11, Loss: 0.24078506231307983
Epoch: 12, Loss: 0.23078124225139618
Epoch: 13, Loss: 0.2220015674829483
Epoch: 14, Loss: 0.21421535313129425
Epoch: 15, Loss: 0.20724867284297943
Epoch: 16, Loss: 0.20096774399280548
Epoch: 17, Loss: 0.19526760280132294
Epoch: 18, Loss: 0.19006462395191193
Epoch: 19, Loss: 0.18529130518436432
Epoch: 20, Loss: 0.18089227378368378
Epoch: 21, Loss: 0.1768217831850052
Epoch: 22, Loss: 0.17304152250289917
Epoch: 23, Loss: 0.16951924562454224
Epoch: 24, Loss: 0.16622740030288696
Epoch: 25, Loss: 0.16314242780208588

In [118]:
model.linear.weight

Parameter containing:
tensor([[ 0.2641,  0.2103,  0.3146,  0.1676,  0.1560,  0.0936,  0.1138,  0.3149,
          0.1430, -0.0902,  0.2719,  0.1120,  0.0087,  0.1776, -0.1373,  0.1134,
          0.0390, -0.0700, -0.0237,  0.0005,  0.1920,  0.2573,  0.3345,  0.4615,
          0.2828,  0.0930,  0.0878,  0.1737,  0.1484,  0.0272]],
       requires_grad=True)

In [119]:
model.linear.bias

Parameter containing:
tensor([-0.1376], requires_grad=True)

In [120]:
# see all parameters (weights + biases) from every layer
for name, param in model.named_parameters():
    print(name, param.shape)

linear.weight torch.Size([1, 30])
linear.bias torch.Size([1])

In [121]:
# training accuracy
with torch.no_grad():
    y_pred_train = model.forward(X_train_tensor)
    y_pred_train = (y_pred_train > 0.5).float().view(-1)
    train_acc = (y_pred_train == y_train_tensor.view(-1)).float().mean()
    print(f'Train Accuracy: {train_acc.item():.4f}')

Train Accuracy: 0.9670

In [122]:
# test on UNSEEN data
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float().view(-1)          
    test_acc = (y_pred == y_test_tensor.view(-1)).float().mean()
    print(f'Test Accuracy: {test_acc.item():.4f}')

Test Accuracy: 0.9474