In [223]:
import numpy as np
import torch
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [224]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [225]:
df.shape

(569, 33)

In [226]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [227]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [228]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [229]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [230]:
X_train

array([[ 0.84684481,  0.2461178 ,  0.75576069, ..., -0.05432276,
         0.55816143, -1.07541527],
       [-0.97829445, -0.20343871, -1.00372704, ..., -1.40962556,
        -0.35986516, -0.92999118],
       [-0.39447661,  0.36198289, -0.37469376, ..., -0.04036336,
        -1.11373075,  0.02316299],
       ...,
       [ 1.34564063,  0.51724209,  1.29739404, ...,  1.42227172,
         1.20205508,  0.77697178],
       [-0.20459411,  0.54968432, -0.24790232, ..., -0.88351122,
        -0.45868053, -0.97247462],
       [ 0.64562604, -0.81057174,  0.55059654, ...,  0.35049988,
        -0.99578984, -0.66092937]], shape=(455, 30))

In [231]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [232]:
y_train

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0])

In [233]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()   
y_train_tensor = torch.from_numpy(y_train).float().view(-1, 1)
y_test_tensor = torch.from_numpy(y_test).float().view(-1, 1)

In [234]:
X_train_tensor.shape

torch.Size([455, 30])

In [235]:

import torch.nn as nn

class MySimpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()

        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [236]:
learning_rate = 0.1
epochs = 25

In [237]:
X_train_tensor.shape[1]

30

In [238]:
model = MySimpleNN(X_train_tensor.shape[1])
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
loss_function = nn.BCELoss()

for epoch in range(epochs):
    # 1. forward pass
    y_pred = model(X_train_tensor)
    
    # 2. loss
    loss = loss_function(y_pred, y_train_tensor)
    
    # 3. clear old gradients
    optimizer.zero_grad()        # replaces manual .grad.zero_()
    
    # 4. backward pass
    loss.backward()
    
    # 5. update weights
    optimizer.step()             # replaces manual w -= lr*grad
    
    print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 1, Loss: 0.5555102229118347
Epoch 2, Loss: 0.2841109335422516
Epoch 3, Loss: 0.20408625900745392
Epoch 4, Loss: 0.1611965000629425
Epoch 5, Loss: 0.1316862404346466
Epoch 6, Loss: 0.11046300828456879
Epoch 7, Loss: 0.09703298658132553
Epoch 8, Loss: 0.0893871858716011
Epoch 9, Loss: 0.08465719223022461
Epoch 10, Loss: 0.08153483271598816
Epoch 11, Loss: 0.07936958223581314
Epoch 12, Loss: 0.07772424072027206
Epoch 13, Loss: 0.07630537450313568
Epoch 14, Loss: 0.07495760172605515
Epoch 15, Loss: 0.07363170385360718
Epoch 16, Loss: 0.07233802229166031
Epoch 17, Loss: 0.07110957056283951
Epoch 18, Loss: 0.06998100876808167
Epoch 19, Loss: 0.0689794197678566
Epoch 20, Loss: 0.06812120229005814
Epoch 21, Loss: 0.0674114003777504
Epoch 22, Loss: 0.06684403121471405
Epoch 23, Loss: 0.06640312075614929
Epoch 24, Loss: 0.0660647377371788
Epoch 25, Loss: 0.06579994410276413

In [239]:
model.linear.weight

Parameter containing:
tensor([[ 0.9918,  1.0580,  0.8231,  0.7164,  0.7075,  0.2237,  0.6070,  0.9189,
          0.3231, -0.9123,  1.1029, -0.2805,  0.8179,  0.9140,  0.1953, -0.2653,
         -0.3142,  0.1087, -0.6299, -0.7742,  1.0706,  1.1089,  1.0434,  1.0107,
          0.8881,  0.3817,  0.4748,  0.9629,  0.9442,  0.2736]],
       requires_grad=True)

In [240]:
model.linear.bias

Parameter containing:
tensor([-1.1841], requires_grad=True)

In [241]:
for p in model.parameters():
    print(p)

Parameter containing:
tensor([[ 0.9918,  1.0580,  0.8231,  0.7164,  0.7075,  0.2237,  0.6070,  0.9189,
          0.3231, -0.9123,  1.1029, -0.2805,  0.8179,  0.9140,  0.1953, -0.2653,
         -0.3142,  0.1087, -0.6299, -0.7742,  1.0706,  1.1089,  1.0434,  1.0107,
          0.8881,  0.3817,  0.4748,  0.9629,  0.9442,  0.2736]],
       requires_grad=True)
Parameter containing:
tensor([-1.1841], requires_grad=True)

In [242]:
# see all parameters (weights + biases) from every layer
for name, param in model.named_parameters():
    print(name, param.shape)

linear.weight torch.Size([1, 30])
linear.bias torch.Size([1])

In [243]:
# training accuracy
with torch.no_grad():
    y_pred_train = model.forward(X_train_tensor)
    y_pred_train = (y_pred_train > 0.5).float().view(-1)
    train_acc = (y_pred_train == y_train_tensor.view(-1)).float().mean()
    print(f'Train Accuracy: {train_acc.item():.4f}')

Train Accuracy: 0.9824

In [244]:
# test on UNSEEN data
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float().view(-1)          
    test_acc = (y_pred == y_test_tensor.view(-1)).float().mean()
    print(f'Test Accuracy: {test_acc.item():.4f}')

Test Accuracy: 0.9825

## torch.optim is a PyTorch module that provides different optimizers.
## Optimizers update the model's weights and bias during training to reduce the loss.

## Common optimizers:
## SGD     -> Simple Gradient Descent optimizer.
## Adam    -> An adaptive optimizer (most commonly used).
## RMSprop -> Optimizer that adapts the learning rate during training.

## torch.optim also supports features like:
## - Learning rate scheduling (changing the learning rate during training)
## - Weight decay (L2 regularization) to help reduce overfitting.

## model.parameters() returns all trainable parameters of the model.
## These parameters include:
## - Weights: The weight matrices of layers like nn.Linear, nn.Conv2d, etc.
## - Biases: The bias values of those layers (if present).

## The optimizer uses these parameters and their gradients
## (computed during backpropagation) to update the model after each training step.

## model.train()   # put model in TRAINING mode (before training loop)
## model.eval()    # put model in EVAL mode (before testing/predicting)