In [575]:
import numpy as np
import torch
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [576]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [577]:
df.shape

(569, 33)

In [578]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [579]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [580]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [581]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [582]:
X_train

array([[-0.54027423,  0.15095457, -0.51436773, ..., -0.50724955,
        -0.28749463,  0.22330521],
       [ 0.26320173,  1.32851757,  0.16515711, ..., -1.31284016,
        -2.16086509, -1.5601289 ],
       [-0.72011362,  1.16648855, -0.73594273, ..., -1.01538177,
         0.58860082, -0.8964882 ],
       ...,
       [ 2.61271629,  0.10303049,  2.55681392, ...,  1.75194387,
         0.03838012, -0.61199436],
       [-1.10879874, -1.06540411, -1.07549372, ..., -1.13042178,
        -0.73782407,  0.03560345],
       [-0.85064221, -1.43738622, -0.87802135, ..., -0.90810423,
        -0.04186039, -0.8820496 ]], shape=(455, 30))

In [583]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [584]:
y_train

array([0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0])

In [585]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()   
y_train_tensor = torch.from_numpy(y_train).float().view(-1, 1)
y_test_tensor = torch.from_numpy(y_test).float().view(-1, 1)

In [586]:
X_train_tensor.shape

torch.Size([455, 30])

In [587]:
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        
        # nn.Sequential - a container that stacks layers and runs them in order
        # data flows top to bottom automatically
        self.network = nn.Sequential(
            nn.Linear(num_features, 1),   # 30 inputs -> 1 output (one neuron)
            nn.Sigmoid()                   # squashes to 0-1 (probability)
        )

    def forward(self, features):
        out = self.network(features)   # one line - Sequential handles the chain
        return out

In [588]:
learning_rate = 0.1
epochs = 25

In [589]:
X_train_tensor.shape[1]

30

In [590]:
model = Model(X_train_tensor.shape[1])
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
loss_function = nn.BCELoss()

for epoch in range(epochs):
    # 1. forward pass
    y_pred = model(X_train_tensor)
    
    # 2. loss
    loss = loss_function(y_pred, y_train_tensor)
    
    # 3. clear old gradients
    optimizer.zero_grad()        # replaces manual .grad.zero_()
    
    # 4. backward pass
    loss.backward()
    
    # 5. update weights
    optimizer.step()             # replaces manual w -= lr*grad
    
    print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 1, Loss: 0.7786151766777039
Epoch 2, Loss: 0.3243306875228882
Epoch 3, Loss: 0.20854763686656952
Epoch 4, Loss: 0.16154217720031738
Epoch 5, Loss: 0.13412946462631226
Epoch 6, Loss: 0.11598151922225952
Epoch 7, Loss: 0.10398228466510773
Epoch 8, Loss: 0.09587287157773972
Epoch 9, Loss: 0.09008277952671051
Epoch 10, Loss: 0.08572816848754883
Epoch 11, Loss: 0.08233654499053955
Epoch 12, Loss: 0.07964707165956497
Epoch 13, Loss: 0.07750460505485535
Epoch 14, Loss: 0.07580748200416565
Epoch 15, Loss: 0.07448150962591171
Epoch 16, Loss: 0.0734659880399704
Epoch 17, Loss: 0.07270533591508865
Epoch 18, Loss: 0.0721442773938179
Epoch 19, Loss: 0.07172660529613495
Epoch 20, Loss: 0.07139796018600464
Epoch 21, Loss: 0.07111041992902756
Epoch 22, Loss: 0.0708264410495758
Epoch 23, Loss: 0.07052063941955566
Epoch 24, Loss: 0.07017922401428223
Epoch 25, Loss: 0.0697980746626854

In [591]:
for p in model.parameters():
    print(p)

Parameter containing:
tensor([[ 0.7951,  1.1091,  0.8097,  0.9625,  0.5709,  0.1746,  0.6581,  0.7895,
          0.1837, -1.1539,  1.1057, -0.0451,  0.7155,  0.9820, -0.0512, -0.0163,
         -0.1672,  0.2357, -0.9505, -0.8603,  0.7562,  1.0171,  1.0040,  0.7406,
          0.8472,  0.4917,  0.5941,  0.8581,  0.6837,  0.0707]],
       requires_grad=True)
Parameter containing:
tensor([-1.0590], requires_grad=True)

In [592]:
# see all parameters (weights + biases) from every layer
for name, param in model.named_parameters():
    print(name, param.shape)

network.0.weight torch.Size([1, 30])
network.0.bias torch.Size([1])

In [593]:
# training accuracy
with torch.no_grad():
    y_pred_train = model.forward(X_train_tensor)
    y_pred_train = (y_pred_train > 0.5).float().view(-1)
    train_acc = (y_pred_train == y_train_tensor.view(-1)).float().mean()
    print(f'Train Accuracy: {train_acc.item():.4f}')

Train Accuracy: 0.9736

In [594]:
# test on UNSEEN data
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float().view(-1)          
    test_acc = (y_pred == y_test_tensor.view(-1)).float().mean()
    print(f'Test Accuracy: {test_acc.item():.4f}')

Test Accuracy: 0.9912

## torch.optim is a PyTorch module that provides different optimizers.
## Optimizers update the model's weights and bias during training to reduce the loss.

## Common optimizers:
## SGD     -> Simple Gradient Descent optimizer.
## Adam    -> An adaptive optimizer (most commonly used).
## RMSprop -> Optimizer that adapts the learning rate during training.

## torch.optim also supports features like:
## - Learning rate scheduling (changing the learning rate during training)
## - Weight decay (L2 regularization) to help reduce overfitting.

## model.parameters() returns all trainable parameters of the model.
## These parameters include:
## - Weights: The weight matrices of layers like nn.Linear, nn.Conv2d, etc.
## - Biases: The bias values of those layers (if present).

## The optimizer uses these parameters and their gradients
## (computed during backpropagation) to update the model after each training step.

## model.train()   # put model in TRAINING mode (before training loop)
## model.eval()    # put model in EVAL mode (before testing/predicting)